apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-creds
  namespace: uptime-kuma-operator
type: Opaque
stringData:
  url: "http://uptime-kuma.example.com:3001"
  user: "admin"
  pass: "password123"
